### ISSUE TITLE
Typo in evaluate_from_loss_table

### ISSUE THREAD

**Issue by habring** [aangelopoulos/im2im-uq#1]
Hey there,

I think in the function evaluate_from_loss_table in calibrate_model.py line 66 should be
`idx_lambda = (RhatPlus <= alpha).nonzero()[0]`
instead of
`idx_lambda = (RhatPlus <= delta).nonzero()[0]`

Maybe I am wrong, but from the paper I think you want RhatPlus to be less than alpha and then delta is the according confidence bound, right?

Best,
Andi

**Comment by aangelopoulos** [comment]
That sounds right to me :)
Thanks for the find.  I'll fix it now.
