### ISSUE TITLE
Error in Hoeffding-Bentkus bound

### ISSUE THREAD

**Issue by habring** [aangelopoulos/im2im-uq#3]
Hello,

I think there might be an error in the computation of the Hoeffding-Bentkus bound:
In bounds.py in the function hoeffding_plus(mu, x, n), line 11, shouldn't the np.maximum be replaced by np.minimum? As it is know, if mu>=x, Hoeffding_plus returns 0. Therefore, whenever mu>muhat in line 19, hoeffding_mu will be zero. But this seems odd, as mu should be the upper confidence bound and in general be larger than muhat, right? Also in your paper https://arxiv.org/pdf/2101.02703.pdf it seems the other way around in Propositions 3,4.

Best,
Andi

**Comment by woctezuma** [comment]
> whenever mu>muhat in line 20, bentkus_mu will be zero

Is it a typo in your post? Indeed:
- based on what you wrote earlier, you might have meant `hoeffding_plus` (line 19),
- it is not super obvious to me that, in this case, `bentkus_plus` (line 20) would be zero.

https://github.com/aangelopoulos/im2im-uq/blob/3b5a5833a6d3a6faacd3f818d8072a8b99116cea/core/calibration/bounds.py#L13-L14

---

For an easier look at the code which you mentioned:

https://github.com/aangelopoulos/im2im-uq/blob/3b5a5833a6d3a6faacd3f818d8072a8b99116cea/core/calibration/bounds.py#L9-L11

https://github.com/aangelopoulos/im2im-uq/blob/3b5a5833a6d3a6faacd3f818d8072a8b99116cea/core/calibration/bounds.py#L16-L26

![Proposition 3](https://i.imgur.com/H1gYQP7.png)

![Proposition 4](https://i.imgur.com/rIeYtsW.png)

**Comment by habring** [comment]
Thanks for the quick response.


> based on what you wrote earlier, you might have meant hoeffding_plus (line 19),

Yes, sorry, I meant line 19 and I meant hoeffding_plus, not bentkus_plus. I'm sorry, not exactly helping to confuse things when trying to point out a possible error.

> it is not super obvious to me that, in this case, bentkus_plus (line 20) would be zero.

- Note that h1(y, mu)=0 whenever y=mu, because log(1)=0.
- Therefore if mu>muhat, then np.maximum(mu,muhat)=mu and therefore in line 19 hoeffding_plus(mu, muhat, n)= -n*h1(np.maximum(mu,muhat),mu)  =  -n*h1(mu,mu) = 0


PS: Shall I update the original Issue to correct this error causing a misunderstanding?

**Comment by woctezuma** [comment]
> PS: Shall I update the original Issue to correct this error causing a misunderstanding?

Yes, I think this would help when the authors read the issue.

**Comment by habring** [comment]
Done :)

**Comment by woctezuma** [comment]
Regarding the issue which you point out, my external perspective is that both cases (minimum or maximum) should work thanks to:

![Picture](https://i.imgur.com/nU02evR.png)

However, the inequality with the max does not bring much information, as `hoeffding_plus()` will return 0 whenever `x < mu`, which should be always the case as you point out (based on my understanding). Similarly, if you take $t = R( \lambda )$, then the inequality becomes $P \le 1$ , which is not super interesting.

So using the minimum would make more sense to me.

Let us wait for inputs from the original author though. 😃

**Comment by habring** [comment]
The problem is, with the maximum, the code piece will either not yield any additional benefit because of what you pointed out: 

> the inequality becomes $P\leq 1$ , which is not super interesting.

But if $t>R(\lambda)$, the code will use the Hoeffding inequality in a setting where it is not allowed according to Proposition 3. I think the point of the minimum/maximum was exactly to take care of the case when Proposition 3 does not apply and the authors might have just confused min with max.

> Let us wait for inputs from the original author though.

Haha yeah!

**Comment by woctezuma** [comment]
> I think the point of the minimum/maximum was exactly to take care of the case when Proposition 3 does not apply and the authors might have just confused min with max.

That would make sense. 👍

**Comment by aangelopoulos** [comment]
Hey @woctezuma and @habring, thanks so much for the input. You are totally right :)
It was a typo. Sorry about that! It can sometimes be a bit of a tongue-twister implementing these bounds...

I'll fix it immediately. And thanks for your wonderful discussion, it helped me remember all the relevant details.
