### ISSUE TITLE
UCB value in algorithm 2

### ISSUE THREAD

**Issue by lironzi** [aangelopoulos/im2im-uq#4]
Hi Anastasios,
I was wondering if there is an error in the paper, or rather I didn't understand the algorithm section.
The UCB value in algorithm 2 gets a value of 1 and immediately after that being evaluated against alpha, which when alpha is 0.1 means the inside of the while loop will never gets executed. 
I believe the value should be 0 and UCB gets bigger with every iteration.
Thanks.
Liron.

**Comment by aangelopoulos** [comment]
Yes, you're exactly right. Thanks for pointing that out.
